import os
from datetime import datetime


class ReportGenerator(object):

    def write(self, result, output_path):
        content = self._render_full(result)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

    def render_summary(self, result):
        fa = result.get("final_action", {})
        params = fa.get("params", {})
        lines = [
            "[Problem Description]{}".format(result.get("problem", "")),
            "[Root Cause]{}".format(params.get("root_cause", "Unknown")),
            "[Conclusion]{}".format(params.get("conclusion", "None")),
            "[Suggestion]",
        ]
        for s in params.get("suggestions", []):
            lines.append("  - {}".format(s))
        lines.append("[Iteration]{}".format(result.get("iterations", 0)))
        return "\n".join(lines)

    def _render_full(self, result):
        fa = result.get("final_action", {})
        params = fa.get("params", {})
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        observations = result.get("observations", [])

        lines = [
            "# Report",
            "",
            "> Generated at: {}".format(now),
            "",
            "## 1. Probelm Description",
            "",
            result.get("problem", ""),
            "",
            "## 2. Diagnostic Procedure",
            "",
        ]

        for i, obs in enumerate(observations, 1):
            obs_type = obs.get("type", "")
            if obs_type == "command":
                lines.append("### Step {}: Run command".format(i))
                lines.append("")
                lines.append("```bash")
                lines.append(obs.get("cmd", ""))
                lines.append("```")
                lines.append("")
                lines.append("**Output:**")
                lines.append("")
                lines.append("```")
                lines.append(obs.get("result", "")[:1000])
                lines.append("```")
            elif obs_type == "log_read":
                lines.append("### Step {}: Read log - {}".format(i, obs.get("source", "")))
                lines.append("")
                lines.append("```")
                lines.append(obs.get("result", "")[:1000])
                lines.append("```")
            elif obs_type == "log_analysis":
                lines.append("### Step {}: Analyze log".format(i))
                lines.append("")
                lines.append(obs.get("result", ""))
            lines.append("")

        lines += [
            "## 3. Root Cause",
            "",
            params.get("root_cause", "Unknown"),
            "",
            "## 4. Conclusion",
            "",
            params.get("conclusion", "None"),
            "",
            "## 5. Suggestion for Next Step",
            "",
        ]
        for s in params.get("suggestions", []):
            lines.append("- {}".format(s))

        lines += [
            "",
            "---",
            "*This report is generated by whatswrong agent. Total {} iterations of diagnostic operation.*".format(result.get("iterations", 0)),
        ]

        return "\n".join(lines)
